### ISSUE TITLE
Create reliance on Yubikey

### ISSUE THREAD

**Issue by shaaarn** [paddeee/farrel#4]
Suggestion - add rule that looks for a password over 32 digits

**Comment by shaaarn** [comment]
From Daggi -

Another alternative is to have a separate field for the yubikey, to mentally separate the password and the hardware tokens from each other to the user. The second field should preferably not echo any \* and combined with your idea would check the length and/or a prefix. In other words, the app checks that there is a password and for example that the user has inserted exactly 35 chars in the separate hardware token field. With both checks satisfied it’s a pretty good indicator that the user has done it correctly.

**Comment by paddeee** [comment]
Sorted
